import { v4 as uuid } from "uuid";
import type { EmailTemplate } from "@/types/builder";

export const STARTER_TEMPLATES: EmailTemplate[] = [
  {
    id: uuid(),
    name: "Product Launch",
    subject: "Introducing Our Latest Product",
    preheader: "You won't want to miss this",
    bodyBackground: "#f4f4f7",
    contentBackground: "#ffffff",
    contentWidth: "600px",
    fontFamily: "Arial, sans-serif",
    elements: [
      {
        id: uuid(),
        type: "image",
        src: "https://placehold.co/600x250/4F46E5/ffffff?text=PRODUCT+LAUNCH",
        alt: "Product launch banner",
        styles: { width: "100%", borderRadius: "0", padding: "0" },
      },
      {
        id: uuid(),
        type: "spacer",
        height: "24px",
        styles: {},
      },
      {
        id: uuid(),
        type: "heading",
        content: "Introducing the All-New Widget Pro",
        level: 1,
        styles: {
          fontSize: "28px",
          color: "#111827",
          textAlign: "center",
          padding: "0 20px",
        },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "We've been working hard behind the scenes, and today we're thrilled to share something special with you. Meet Widget Pro — redesigned from the ground up to be faster, smarter, and more beautiful than ever.",
        styles: {
          fontSize: "16px",
          color: "#4b5563",
          textAlign: "center",
          padding: "12px 20px",
          lineHeight: "1.6",
        },
      },
      {
        id: uuid(),
        type: "button",
        text: "Learn More",
        link: "https://example.com",
        buttonColor: "#4F46E5",
        textColor: "#ffffff",
        borderRadius: "8px",
        styles: { textAlign: "center", padding: "16px 0", fontSize: "16px" },
      },
      {
        id: uuid(),
        type: "spacer",
        height: "12px",
        styles: {},
      },
      {
        id: uuid(),
        type: "divider",
        thickness: "1px",
        dividerColor: "#e5e7eb",
        dividerWidth: "80%",
        styles: { padding: "8px 0" },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "You're receiving this email because you signed up at example.com. Unsubscribe at any time.",
        styles: {
          fontSize: "12px",
          color: "#9ca3af",
          textAlign: "center",
          padding: "12px 20px",
          lineHeight: "1.5",
        },
      },
    ],
  },
  {
    id: uuid(),
    name: "Newsletter",
    subject: "This Week's Newsletter",
    preheader: "Top stories and updates from this week",
    bodyBackground: "#f8fafc",
    contentBackground: "#ffffff",
    contentWidth: "600px",
    fontFamily: "Georgia, serif",
    elements: [
      {
        id: uuid(),
        type: "heading",
        content: "THE WEEKLY DIGEST",
        level: 1,
        styles: {
          fontSize: "24px",
          color: "#0f172a",
          textAlign: "center",
          padding: "24px 0 8px",
          fontWeight: "bold",
        },
      },
      {
        id: uuid(),
        type: "text",
        content: "February 28, 2026 — Issue #42",
        styles: {
          fontSize: "13px",
          color: "#94a3b8",
          textAlign: "center",
          padding: "0 0 16px",
        },
      },
      {
        id: uuid(),
        type: "divider",
        thickness: "2px",
        dividerColor: "#0f172a",
        dividerWidth: "60px",
        styles: { padding: "4px 0" },
      },
      {
        id: uuid(),
        type: "image",
        src: "https://placehold.co/560x280/e2e8f0/475569?text=Featured+Story",
        alt: "Featured story image",
        styles: { width: "100%", borderRadius: "12px", padding: "16px 0 8px" },
      },
      {
        id: uuid(),
        type: "heading",
        content: "Featured: The Future of Design Systems",
        level: 2,
        styles: {
          fontSize: "22px",
          color: "#0f172a",
          textAlign: "left",
          padding: "8px 0 4px",
        },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "As design systems continue to evolve, we look at the emerging patterns that are shaping how teams collaborate and build products. From token-based theming to AI-assisted component generation, the landscape is changing fast.",
        styles: {
          fontSize: "15px",
          color: "#475569",
          padding: "4px 0 12px",
          lineHeight: "1.7",
        },
      },
      {
        id: uuid(),
        type: "button",
        text: "Read Full Story",
        link: "https://example.com",
        buttonColor: "#0f172a",
        textColor: "#ffffff",
        borderRadius: "6px",
        styles: { textAlign: "left", padding: "4px 0" },
      },
      {
        id: uuid(),
        type: "spacer",
        height: "20px",
        styles: {},
      },
      {
        id: uuid(),
        type: "divider",
        thickness: "1px",
        dividerColor: "#e2e8f0",
        dividerWidth: "100%",
        styles: { padding: "4px 0" },
      },
      {
        id: uuid(),
        type: "heading",
        content: "More Stories",
        level: 3,
        styles: {
          fontSize: "18px",
          color: "#0f172a",
          textAlign: "left",
          padding: "12px 0 4px",
        },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "1. How to Build Accessible Email Templates\n2. Color Theory in Digital Communications\n3. Typography Trends for 2026\n4. A/B Testing Strategies That Actually Work",
        styles: {
          fontSize: "15px",
          color: "#475569",
          padding: "4px 0 16px",
          lineHeight: "2",
        },
      },
      {
        id: uuid(),
        type: "divider",
        thickness: "1px",
        dividerColor: "#e2e8f0",
        dividerWidth: "100%",
        styles: { padding: "4px 0" },
      },
      {
        id: uuid(),
        type: "social",
        links: [
          {
            platform: "Twitter",
            url: "https://twitter.com",
            icon: "https://placehold.co/32/1DA1F2/fff?text=X",
          },
          {
            platform: "Facebook",
            url: "https://facebook.com",
            icon: "https://placehold.co/32/1877F2/fff?text=f",
          },
          {
            platform: "Instagram",
            url: "https://instagram.com",
            icon: "https://placehold.co/32/E4405F/fff?text=IG",
          },
        ],
        iconSize: "28px",
        styles: { textAlign: "center", padding: "16px 0" },
      },
      {
        id: uuid(),
        type: "text",
        content: "You received this email because you subscribed to The Weekly Digest. Unsubscribe here.",
        styles: {
          fontSize: "11px",
          color: "#94a3b8",
          textAlign: "center",
          padding: "4px 0 16px",
        },
      },
    ],
  },
  {
    id: uuid(),
    name: "Sale / Promo",
    subject: "48-Hour Flash Sale — Up to 50% Off",
    preheader: "Don't miss our biggest sale of the season",
    bodyBackground: "#111827",
    contentBackground: "#1f2937",
    contentWidth: "600px",
    fontFamily: "Arial, sans-serif",
    elements: [
      {
        id: uuid(),
        type: "spacer",
        height: "20px",
        styles: {},
      },
      {
        id: uuid(),
        type: "heading",
        content: "FLASH SALE",
        level: 1,
        styles: {
          fontSize: "40px",
          color: "#fbbf24",
          textAlign: "center",
          padding: "12px 0 0",
          fontWeight: "bold",
        },
      },
      {
        id: uuid(),
        type: "heading",
        content: "UP TO 50% OFF EVERYTHING",
        level: 2,
        styles: {
          fontSize: "20px",
          color: "#ffffff",
          textAlign: "center",
          padding: "4px 0 16px",
        },
      },
      {
        id: uuid(),
        type: "timer",
        targetDate: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
        label: "Sale ends in",
        timerColor: "#dc2626",
        labelColor: "#9ca3af",
        styles: { padding: "8px 0 20px" },
      },
      {
        id: uuid(),
        type: "image",
        src: "https://placehold.co/560x300/374151/f9fafb?text=SHOP+NOW",
        alt: "Sale products",
        styles: { width: "100%", borderRadius: "12px", padding: "8px 0" },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "For 48 hours only, enjoy massive discounts across our entire collection. This is our biggest sale of the season — use code FLASH50 at checkout.",
        styles: {
          fontSize: "16px",
          color: "#d1d5db",
          textAlign: "center",
          padding: "12px 24px",
          lineHeight: "1.6",
        },
      },
      {
        id: uuid(),
        type: "button",
        text: "Shop the Sale",
        link: "https://example.com/sale",
        buttonColor: "#fbbf24",
        textColor: "#111827",
        borderRadius: "999px",
        styles: { textAlign: "center", padding: "16px 0", fontSize: "16px" },
      },
      {
        id: uuid(),
        type: "spacer",
        height: "16px",
        styles: {},
      },
      {
        id: uuid(),
        type: "text",
        content: "Free shipping on orders over $50 • Easy 30-day returns",
        styles: {
          fontSize: "13px",
          color: "#6b7280",
          textAlign: "center",
          padding: "8px 0 20px",
        },
      },
    ],
  },
  {
    id: uuid(),
    name: "Welcome Email",
    subject: "Welcome to the Team!",
    preheader: "We're so glad you're here",
    bodyBackground: "#faf5ff",
    contentBackground: "#ffffff",
    contentWidth: "600px",
    fontFamily: "Arial, sans-serif",
    elements: [
      {
        id: uuid(),
        type: "spacer",
        height: "24px",
        styles: {},
      },
      {
        id: uuid(),
        type: "heading",
        content: "Welcome aboard!",
        level: 1,
        styles: {
          fontSize: "32px",
          color: "#7c3aed",
          textAlign: "center",
          padding: "0 20px",
        },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "We're absolutely thrilled to have you join us. You've just unlocked access to tools, templates, and a community that will help you create amazing things.",
        styles: {
          fontSize: "16px",
          color: "#374151",
          textAlign: "center",
          padding: "12px 24px",
          lineHeight: "1.7",
        },
      },
      {
        id: uuid(),
        type: "divider",
        thickness: "1px",
        dividerColor: "#e5e7eb",
        dividerWidth: "40%",
        styles: { padding: "8px 0" },
      },
      {
        id: uuid(),
        type: "heading",
        content: "Here's what to do next:",
        level: 3,
        styles: {
          fontSize: "18px",
          color: "#111827",
          textAlign: "left",
          padding: "8px 0 4px",
        },
      },
      {
        id: uuid(),
        type: "text",
        content:
          "1. Complete your profile\n2. Explore the template gallery\n3. Create your first design\n4. Invite your team members",
        styles: {
          fontSize: "15px",
          color: "#4b5563",
          padding: "4px 0 16px",
          lineHeight: "2",
        },
      },
      {
        id: uuid(),
        type: "button",
        text: "Get Started",
        link: "https://example.com/onboarding",
        buttonColor: "#7c3aed",
        textColor: "#ffffff",
        borderRadius: "8px",
        styles: { textAlign: "center", padding: "8px 0" },
      },
      {
        id: uuid(),
        type: "spacer",
        height: "24px",
        styles: {},
      },
      {
        id: uuid(),
        type: "text",
        content:
          "Need help getting started? Reply to this email or visit our help center.",
        styles: {
          fontSize: "13px",
          color: "#9ca3af",
          textAlign: "center",
          padding: "0 20px 20px",
        },
      },
    ],
  },
];
